


include(render/render.pri)
include(rpc/rpc.pri)
include(utils/utils.pri)
include(helpers/helpers.pri)

HEADERS += \
        $$PWD/const.h \
        $$PWD/db/Avatar.h \
        $$PWD/db/Database.h \
        $$PWD/db/db_utils.h \
        $$PWD/db/GameTableSettingsData.h \
        $$PWD/db/modeldatabase.h \
        $$PWD/db/SettingsDatabase.h \
        $$PWD/db/SharedDataService.h \
        $$PWD/delegates/delegate_customcolumn.h \
        $$PWD/delegates/delegate_GameTableComboBoxItem.h \
        $$PWD/descriptors/descriptor_CashBuyIn.h \
        $$PWD/descriptors/descriptor_GameTable.h \
        $$PWD/descriptors/descriptor_SitNGoBuyIn.h \
        $$PWD/descriptors/descriptor_SpinNGoBuyIn.h \
        $$PWD/descriptors/descriptor_TournamentBuyIn.h \
        $$PWD/dialogs/buyin/dialog_CashBuyIn.h \
        $$PWD/dialogs/buyin/dialog_TournamentBuyIn.h \
        $$PWD/dialogs/dialog_account.h \
        $$PWD/dialogs/dialog_authorization.h \
        $$PWD/dialogs/dialog_changeavatar.h \
        $$PWD/dialogs/dialog_gametable.h \
        $$PWD/dialogs/dialog_okmessage.h \
        $$PWD/dialogs/dialog_onerror.h \
        $$PWD/dialogs/dialog_tablesettings.h \
        $$PWD/dialogs/lobby/dialog_LobbyBase.h \
        $$PWD/dialogs/lobby/dialog_LobbySitNGo.h \
        $$PWD/dialogs/lobby/dialog_LobbyTournament.h \
        $$PWD/dialogs/menubar/dialog_mytournaments.h \
        $$PWD/dialogs/menubar/dialog_settings.h \
        $$PWD/dialogs/menubar/dialog_vipsystem.h \
        $$PWD/editors/ColorMatrixEditor.h \
        $$PWD/game/actions/actions_fwd.hpp \
        $$PWD/game/actions/complex_actions.h \
        $$PWD/game/actions/single_actions.h \
        $$PWD/game/actions/subqueue_actions.h \
#        $$PWD/game/cashhandler.h \
        $$PWD/game/commongameviewhandler.h \
        $$PWD/game/controls/usercontrols.h \
        $$PWD/game/controlshandler.h \
        $$PWD/game/debuginfoprintergamehandler.h \
        $$PWD/game/ErrorHandler.h \
        $$PWD/game/gamehandlerinterface.hpp \
        $$PWD/game/GameManager.h \
        $$PWD/game/NotificationHandler.h \
        $$PWD/game/PlayersManager.h \
        $$PWD/game/proxydatahandler.h \
        $$PWD/game/proxyhandler.h \
        $$PWD/game/proxyviewhandler.h \
        $$PWD/game/signatureadapter.h \
        $$PWD/game/tabledataupdater.h \
        $$PWD/game/tableItems/betitem.h \
        $$PWD/game/tableItems/modelkeyitem.h \
        $$PWD/game/tableItems/panel_BetControls.h \
        $$PWD/game/tableItems/potitem.h \
        $$PWD/game/TimelineHandler.h \
        $$PWD/game/userbox.h \
        $$PWD/interface/identifiable.h \
        $$PWD/interface/initable.h \
        $$PWD/interface/NetworkHandlers.h \
        $$PWD/models/lobbyTournament/model_LobbyBase.h \
        $$PWD/models/lobbyTournament/model_LobbyCommonInfo.h \
        $$PWD/models/lobbyTournament/model_QualifiersTable.h \
        $$PWD/models/model_AvatarsList.h \
        $$PWD/models/model_CardsDeck.h \
        $$PWD/models/model_cashtables.h \
        $$PWD/models/model_Chat.h \
        $$PWD/models/model_ChatSmilesList.h \
        $$PWD/models/model_Filters.h \
        $$PWD/models/model_GamesStatistic.h \
        $$PWD/models/model_PlayersListModel.h \
        $$PWD/models/model_PlayersTable.h \
        $$PWD/models/model_RakebackHistory.h \
        $$PWD/models/model_TableSettings.h \
        $$PWD/models/model_tournaments.h \
        $$PWD/models/model_user_additional_info.h \
        $$PWD/models/model_user_additional_info_items.hpp \
        $$PWD/models/model_VipStatusInfo.h \
        $$PWD/models/proxy/model_commongametable.h \
        $$PWD/models/proxy/model_FunctionFilter.h \
        $$PWD/models/proxy/model_modelcontainer.h \
        $$PWD/models/proxy/model_singlecolumn.h \
        $$PWD/pages/lobbyTournament/page_LobbyBase.h \
        $$PWD/pages/lobbyTournament/page_LobbyBlinds.h \
        $$PWD/pages/lobbyTournament/page_LobbyCommonInfo.h \
        $$PWD/pages/lobbyTournament/page_LobbyPlayers.h \
        $$PWD/pages/lobbyTournament/page_LobbyPrizes.h \
        $$PWD/pages/lobbyTournament/page_LobbyTables.h \
        $$PWD/pages/lobbyTournament/page_Qualifiers.h \
        $$PWD/pages/mainLobby/page_CashTables.h \
        $$PWD/pages/mainLobby/page_MainLobbyBase.h \
        $$PWD/pages/mainLobby/page_SitNGo.h \
        $$PWD/pages/mainLobby/page_SpinNGo.h \
        $$PWD/pages/mainLobby/page_Tournaments.h \
        $$PWD/pages/page_MainScreen.h \
        $$PWD/pages/page_SelectAvatar.h \
        $$PWD/pages/page_UploadAvatar.h \
        $$PWD/pages/settings/page_SettingsAutorebuy.h \
        $$PWD/pages/settings/page_SettingsBase.h \
        $$PWD/pages/settings/page_SettingsCommon.h \
        $$PWD/pages/settings/page_SettingsHistory.h \
        $$PWD/pages/settings/page_SettingsNotes.h \
        $$PWD/pages/vipSystem/page_VipStatusDescription.h \
        $$PWD/pages/vipSystem/page_VipStatusItem.h \
        $$PWD/pages/vipSystem/page_VipSystemDescription.h \
        $$PWD/PokerApplication.h \
        $$PWD/settingsmanager.h \
        $$PWD/views/AvatarsListWidget.h \
        $$PWD/widgets/CalendarItem.h \
        $$PWD/widgets/CardWidget.h \
        $$PWD/widgets/DropArea.h \
        $$PWD/widgets/GameTablePreview.h \
        $$PWD/widgets/GameTableToolBar.h \
        $$PWD/widgets/GLWidget.h \
        $$PWD/widgets/MainWindow.h \
        $$PWD/widgets/MoneySlider.h \
        $$PWD/widgets/MoneySpinBox.h \
        $$PWD/widgets/panel_Description.h \
        $$PWD/widgets/panel_SitNGoDescription.h \
        $$PWD/widgets/panel_TournDescription.h \
        $$PWD/widgets/PasswordToolTip.h \
        $$PWD/widgets/PixmapEditor.h \
        $$PWD/widgets/StatisticTableView.h \
        $$PWD/widgets/widget_BetScrollBar.h \
        $$PWD/widgets/widget_LanguageItem.h \
        $$PWD/widgets/widget_MiniTable.h \
        $$PWD/widgets/widget_MoneyButton.h \
        $$PWD/widgets/widget_PlayerInfo.h \
        $$PWD/widgets/widget_ProfilePicture.h \
        $$PWD/widgets/widget_TableOver.h \
        $$PWD/game/abstractgamehandler.h \
        $$PWD/game/actions/user_triggered_actions.h \
        $$PWD/game/actions/updater_actions.h \
        $$PWD/dialogs/dialog_server_not_available.h

SOURCES += \
        $$PWD/db/Avatar.cpp \
        $$PWD/db/Database.cpp \
        $$PWD/db/db_utils.cpp \
        $$PWD/db/GameTableSettingsData.cpp \
        $$PWD/db/modeldatabase.cpp \
        $$PWD/db/SettingsDatabase.cpp \
        $$PWD/db/SharedDataService.cpp \
        $$PWD/delegates/delegate_customcolumn.cpp \
        $$PWD/delegates/delegate_GameTableComboBoxItem.cpp \
        $$PWD/dialogs/buyin/dialog_CashBuyIn.cpp \
        $$PWD/dialogs/buyin/dialog_TournamentBuyIn.cpp \
        $$PWD/dialogs/dialog_account.cpp \
        $$PWD/dialogs/dialog_authorization.cpp \
        $$PWD/dialogs/dialog_changeavatar.cpp \
        $$PWD/dialogs/dialog_gametable.cpp \
        $$PWD/dialogs/dialog_okmessage.cpp \
        $$PWD/dialogs/dialog_onerror.cpp \
        $$PWD/dialogs/dialog_tablesettings.cpp \
        $$PWD/dialogs/lobby/dialog_LobbyBase.cpp \
        $$PWD/dialogs/lobby/dialog_LobbySitNGo.cpp \
        $$PWD/dialogs/lobby/dialog_LobbyTournament.cpp \
        $$PWD/dialogs/menubar/dialog_mytournaments.cpp \
        $$PWD/dialogs/menubar/dialog_settings.cpp \
        $$PWD/dialogs/menubar/dialog_vipsystem.cpp \
        $$PWD/editors/ColorMatrixEditor.cpp \
        $$PWD/game/actions/complex_actions.cpp \
        $$PWD/game/actions/single_actions.cpp \
        $$PWD/game/actions/subqueue_actions.cpp \
#        $$PWD/game/cashhandler.cpp \
        $$PWD/game/commongameviewhandler.cpp \
        $$PWD/game/controls/usercontrols.cpp \
        $$PWD/game/controlshandler.cpp \
        $$PWD/game/debuginfoprintergamehandler.cpp \
        $$PWD/game/GameManager.cpp \
        $$PWD/game/NotificationHandler.cpp \
        $$PWD/game/PlayersManager.cpp \
        $$PWD/game/proxydatahandler.cpp \
        $$PWD/game/proxyhandler.cpp \
        $$PWD/game/proxyviewhandler.cpp \
        $$PWD/game/tabledataupdater.cpp \
        $$PWD/game/tableItems/betitem.cpp \
        $$PWD/game/tableItems/modelkeyitem.cpp \
        $$PWD/game/tableItems/panel_BetControls.cpp \
        $$PWD/game/tableItems/potitem.cpp \
        $$PWD/game/TimelineHandler.cpp \
        $$PWD/game/userbox.cpp \
        $$PWD/interface/identifiable.cpp \
        $$PWD/interface/initable.cpp \
        $$PWD/main.cpp \
        $$PWD/models/lobbyTournament/model_LobbyBase.cpp \
        $$PWD/models/lobbyTournament/model_LobbyCommonInfo.cpp \
        $$PWD/models/lobbyTournament/model_QualifiersTable.cpp \
        $$PWD/models/model_AvatarsList.cpp \
        $$PWD/models/model_CardsDeck.cpp \
        $$PWD/models/model_cashtables.cpp \
        $$PWD/models/model_Chat.cpp \
        $$PWD/models/model_ChatSmilesList.cpp \
        $$PWD/models/model_Filters.cpp \
        $$PWD/models/model_GamesStatistic.cpp \
        $$PWD/models/model_PlayersListModel.cpp \
        $$PWD/models/model_PlayersTable.cpp \
        $$PWD/models/model_RakebackHistory.cpp \
        $$PWD/models/model_TableSettings.cpp \
        $$PWD/models/model_tournaments.cpp \
        $$PWD/models/model_user_additional_info.cpp \
        $$PWD/models/model_user_additional_info_items.cpp \
        $$PWD/models/model_VipStatusInfo.cpp \
        $$PWD/models/proxy/model_commongametable.cpp \
        $$PWD/models/proxy/model_FunctionFilter.cpp \
        $$PWD/models/proxy/model_modelcontainer.cpp \
        $$PWD/models/proxy/model_singlecolumn.cpp \
        $$PWD/pages/lobbyTournament/page_LobbyBase.cpp \
        $$PWD/pages/lobbyTournament/page_LobbyBlinds.cpp \
        $$PWD/pages/lobbyTournament/page_LobbyCommonInfo.cpp \
        $$PWD/pages/lobbyTournament/page_LobbyPlayers.cpp \
        $$PWD/pages/lobbyTournament/page_LobbyPrizes.cpp \
        $$PWD/pages/lobbyTournament/page_LobbyTables.cpp \
        $$PWD/pages/lobbyTournament/page_Qualifiers.cpp \
        $$PWD/pages/mainLobby/page_CashTables.cpp \
        $$PWD/pages/mainLobby/page_MainLobbyBase.cpp \
        $$PWD/pages/mainLobby/page_SitNGo.cpp \
        $$PWD/pages/mainLobby/page_SpinNGo.cpp \
        $$PWD/pages/mainLobby/page_Tournaments.cpp \
        $$PWD/pages/page_MainScreen.cpp \
        $$PWD/pages/page_SelectAvatar.cpp \
        $$PWD/pages/page_UploadAvatar.cpp \
        $$PWD/pages/settings/page_SettingsAutorebuy.cpp \
        $$PWD/pages/settings/page_SettingsBase.cpp \
        $$PWD/pages/settings/page_SettingsCommon.cpp \
        $$PWD/pages/settings/page_SettingsHistory.cpp \
        $$PWD/pages/settings/page_SettingsNotes.cpp \
        $$PWD/pages/vipSystem/page_VipStatusDescription.cpp \
        $$PWD/pages/vipSystem/page_VipStatusItem.cpp \
        $$PWD/pages/vipSystem/page_VipSystemDescription.cpp \
        $$PWD/PokerApplication.cpp \
        $$PWD/precompiled.cpp \
        $$PWD/settingsmanager.cpp \
        $$PWD/views/AvatarsListWidget.cpp \
        $$PWD/widgets/CalendarItem.cpp \
        $$PWD/widgets/CardWidget.cpp \
        $$PWD/widgets/DropArea.cpp \
        $$PWD/widgets/GameTablePreview.cpp \
        $$PWD/widgets/GameTableToolBar.cpp \
        $$PWD/widgets/GLWidget.cpp \
        $$PWD/widgets/MainWindow.cpp \
        $$PWD/widgets/MoneySlider.cpp \
        $$PWD/widgets/MoneySpinBox.cpp \
        $$PWD/widgets/panel_Description.cpp \
        $$PWD/widgets/panel_SitNGoDescription.cpp \
        $$PWD/widgets/panel_TournDescription.cpp \
        $$PWD/widgets/PasswordToolTip.cpp \
        $$PWD/widgets/PixmapEditor.cpp \
        $$PWD/widgets/StatisticTableView.cpp \
        $$PWD/widgets/widget_BetScrollBar.cpp \
        $$PWD/widgets/widget_LanguageItem.cpp \
        $$PWD/widgets/widget_MiniTable.cpp \
        $$PWD/widgets/widget_MoneyButton.cpp \
        $$PWD/widgets/widget_PlayerInfo.cpp \
        $$PWD/widgets/widget_ProfilePicture.cpp \
        $$PWD/widgets/widget_TableOver.cpp \
        $$PWD/game/abstractgamehandler.cpp \
        $$PWD/game/actions/user_triggered_actions.cpp \
        $$PWD/game/actions/updater_actions.cpp \
        $$PWD/dialogs/dialog_server_not_available.cpp

!contains(DEFINES, NO_REGISTRATION) {
    HEADERS += $$PWD/dialogs/dialog_welcome.h \
               $$PWD/dialogs/dialog_registration.h

    SOURCES += $$PWD/dialogs/dialog_welcome.cpp \
               $$PWD/dialogs/dialog_registration.cpp

    FORMS += $$PWD/../data/forms/dialog_Registration.ui \
             $$PWD/../data/forms/dialog_Welcome.ui

}
